/* GET related */
export const GETALL_REQUEST = 'USERS_GETALL_REQUEST';
export const GETALL_SUCCESS = 'USERS_GETALL_SUCCESS';
export const GETALL_FAILURE = 'USERS_GETALL_FAILURE';
/* Register related */
export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';
/* Login related */
export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';
/* Logout related */
export const LOGOUT = 'USERS_LOGOUT';
/* Modal related */
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
/* Data related */
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
/*Alerts */
export const SUCCESS = 'ALERT_SUCCESS';
export const ERROR = 'ALERT_ERROR';
export const CLEAR = 'ALERT_CLEAR';
/* ITEMS ADD RELATED */
export const ADDITEM_REQUEST = 'USERS_ADDITEM_REQUEST';
export const ADDITEM_SUCCESS = 'USERS_ADDITEM_SUCCESS';
export const ADDITEM_FAILURE = 'USERS_ADDITEM_FAILURE';
/* ITEMS EDIT RELATED */
export const EDITITEM_REQUEST = 'USERS_EDITITEM_REQUEST';
export const EDITITEM_SUCCESS = 'USERS_EDITITEM_SUCCESS';
export const EDITITEM_FAILURE = 'USERS_EDITITEM_FAILURE';
/* ITEMS DELETE RELATED */
export const DELETEITEM_REQUEST = 'USERS_DELETEITEM_REQUEST';
export const DELETEITEM_SUCCESS = 'USERS_DELETEITEM_SUCCESS';
export const DELETEITEM_FAILURE = 'USERS_DELETEITEM_FAILURE';
/* ITEMS UPDATED RELATED */
export const UPDATESTATE = 'UPDATEDSTATE';
export const UPDATEEVENT = 'UPDATEEVENT';
/*CALENDAR EVENT RELATED */
export const SETDATE = 'SETDATE';
