/* GET related */
export const GETALL_REQUEST = 'GETALL_REQUEST';
export const GETALL_SUCCESS = 'GETALL_SUCCESS';
export const GETALL_FAILURE = 'GETALL_FAILURE';
/* Register related */
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
/* Login related */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
/* Logout related */
export const LOGOUT = 'LOGOUT';
/* Modal related */
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
/* Data related */
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
/*Alerts */
export const SUCCESS = 'ALERT_SUCCESS';
export const ERROR = 'ALERT_ERROR';
export const CLEAR = 'ALERT_CLEAR';
/* ITEMS ADD RELATED */
export const ADDITEM_REQUEST = 'ADDITEM_REQUEST';
export const ADDITEM_SUCCESS = 'ADDITEM_SUCCESS';
export const ADDITEM_FAILURE = 'ADDITEM_FAILURE';
/* ITEMS EDIT RELATED */
export const EDITITEM_REQUEST = 'EDITITEM_REQUEST';
export const EDITITEM_SUCCESS = 'EDITITEM_SUCCESS';
export const EDITITEM_FAILURE = 'EDITITEM_FAILURE';
/* ITEMS DELETE RELATED */
export const DELETEITEM_REQUEST = 'DELETEITEM_REQUEST';
export const DELETEITEM_SUCCESS = 'DELETEITEM_SUCCESS';
export const DELETEITEM_FAILURE = 'DELETEITEM_FAILURE';
/* ITEMS UPDATED RELATED */
export const UPDATESTATE = 'UPDATEDSTATE';
export const UPDATEEVENT = 'UPDATEEVENT';
/*CALENDAR EVENT RELATED */
export const SETDATE = 'SETDATE';
export const FILTEREVENTS = 'FILTEREVENTS'
